### ISSUE TITLE
issues with rOpenserver with IPM11 build 194

### ISSUE THREAD

**Issue by nicovog** [f0nzie/rOpenserver#1]
First of all, I really like the rOpenserver package; very useful! 

Everything worked fine, until I recently updated my IPM suite to IPM11 build 194, after which I now get the following error when I run a script with rOpenserver. It seems to connect and open Prosper, but doesn't feedback to it... Can you please advise what to do with this issue? Thanks in advance!

<checkErrorInfo> 80020008 
No support for ISupportErrorInfo
checkErrorInfo -2147352568
Error: Bad variable type.

**Comment by f0nzie** [comment]
@nicovog Thanks for using rOpenserver.
Regarding the error with IPM11, I wouldn’t know.
The package is based on IPM 7.5 through IPM10, from the time I was working for Petronas.
I don’t have access to IMP11. Sorry about that.
If you give me remote access to your IPM11, I may be able to help.

**Comment by nicovog** [comment]
@f0nzie, thanks for your quick reply! I have resolved the issue by reinstalling both IPM (version 11 build 194) and R (version 3.5.3). Works good again!
